### PR TITLE
Update ui.R

### PR DESCRIPTION
**Pull request by chaninn**
The latest version of FPOP website.

### CODE REVIEW

**Comment by sawsimeon** [comment]
thanks boss, help me think boss, how can i read the fasta from a text box of ui R to sever R. May be read.fasta function from protr but boss i make the ui text box with tag$text... any idea boss. For submit for controlling the overall interaction is doable i think

**Comment by chaninn** [comment]
Since you have 2 methods for users to input their data, then there must be
some form of "if" flow such as:
If user enter their sequence in the text box then assign the entered
content into a specific variable and use this variable for further
descriptor calculation, "else if" user upload their file then use this to
generate the descriptors (which you had already implemented), "else" return
a warning that no FASTA text or file has been inputed.

On Fri, May 8, 2015 at 11:30 PM, Saw Simeon notifications@github.com
wrote:

> thanks boss, help me think boss, how can i read the fasta from a text box
> of ui R to sever R. May be read.fasta function from protr but boss i make
> the ui text box with tag$text... any idea boss. For submit for controlling
> the overall interaction is doable i think
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rnewbie/OliFP/pull/3#issuecomment-100287562.

## 

Associate Professor Chanin Nantasenamat, Ph.D.
Head, Center of Data Mining and Biomedical Informatics
Faculty of Medical Technology, Mahidol University
999 Phutthamonthon 4 Road, Salaya, Nakhon Pathom 73170
Tel. 02 441 4371 ext 2715
Fax 02 441 4380

**Comment by sawsimeon** [comment]
Boss  you mean like this right?

if (sequence on text box) {
Read fasta...
} else if (fasta in choose file) {
Read fasta...
} else {
Please insert fasta...
}

**Comment by sawsimeon** [comment]
Boss i am thinking of a variable from textbox of  ui R to link to server. I mean the some variable that will allow server to grap. is it a tag$textarea. I dont really know

**Comment by sawsimeon** [comment]
Please help me

**Comment by sawsimeon** [comment]
Sleep tight boss. Calll it a day. Good night.

**Comment by chaninn** [comment]
Try:
http://stackoverflow.com/questions/28391184/shiny-binding-for-textarea-cannot-set-initial-value

inside tag$textarea you set the value of the 'id' field so you can use the
resulting id value to call in server.R isn't that right?

On Fri, May 8, 2015 at 11:55 PM, Saw Simeon notifications@github.com
wrote:

> Boss i am thinking of a variable from textbox of ui R to link to server. I
> mean the some variable that will allow server to grap. is it a
> tag$textarea. I dont really know
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rnewbie/OliFP/pull/3#issuecomment-100297710.

## 

Associate Professor Chanin Nantasenamat, Ph.D.
Head, Center of Data Mining and Biomedical Informatics
Faculty of Medical Technology, Mahidol University
999 Phutthamonthon 4 Road, Salaya, Nakhon Pathom 73170
Tel. 02 441 4371 ext 2715
Fax 02 441 4380

**Comment by chaninn** [comment]
Also worth to look at:
http://stackoverflow.com/questions/27239148/cols-does-not-work-in-tagstextarea-of-a-shiny-application

On Sat, May 9, 2015 at 12:14 AM, Chanin Nantasenamat <chanin.nan@mahidol.edu

> wrote:
> 
> Try:
> 
> http://stackoverflow.com/questions/28391184/shiny-binding-for-textarea-cannot-set-initial-value
> 
> inside tag$textarea you set the value of the 'id' field so you can use the
> resulting id value to call in server.R isn't that right?
> 
> On Fri, May 8, 2015 at 11:55 PM, Saw Simeon notifications@github.com
> wrote:
> 
> > Boss i am thinking of a variable from textbox of ui R to link to server.
> > I mean the some variable that will allow server to grap. is it a
> > tag$textarea. I dont really know
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Rnewbie/OliFP/pull/3#issuecomment-100297710.
> 
> ## 
> 
> Associate Professor Chanin Nantasenamat, Ph.D.
> Head, Center of Data Mining and Biomedical Informatics
> Faculty of Medical Technology, Mahidol University
> 999 Phutthamonthon 4 Road, Salaya, Nakhon Pathom 73170
> Tel. 02 441 4371 ext 2715
> Fax 02 441 4380

## 

Associate Professor Chanin Nantasenamat, Ph.D.
Head, Center of Data Mining and Biomedical Informatics
Faculty of Medical Technology, Mahidol University
999 Phutthamonthon 4 Road, Salaya, Nakhon Pathom 73170
Tel. 02 441 4371 ext 2715
Fax 02 441 4380

**Comment by sawsimeon** [comment]
Will look at them. Thanks

**Pull request merged**
